### ISSUE TITLE
dotenv to setup custom configuration per event

### ISSUE THREAD

**Issue by wizbright** [katerberg/9th-seed#1]
Using [dotenv](https://www.npmjs.com/package/dotenv) and allowing links and other customize-able options easily configured in a file.
```
# Documents
GOOG_SPREADSHEET=foo.bar
CHALLONGE=fizz.buzz
# Custom vars
FOO=bar
```

**Comment by katerberg** [comment]
This should include things like:

- Which channels for 9th Seed to attach to
- Whether to start in debug mode
- All simple messages (single input, single response)

**Comment by wizbright** [comment]
We can honestly put most of the creds in a `.env` and keep most of the messages and other text and links in json format as you have already with the current creds.

**Comment by katerberg** [comment]
Done as a first step, but could use additions

**Comment by katerberg** [comment]
Closing this out since it's now using parts of it. If there's particular things that should be pulled out, then having issues/PRs for those individually would be great!
